repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: src/dbt/
      - id: end-of-file-fixer
        exclude: src/dbt/
      - id: check-yaml
        exclude: src/dbt/
      - id: check-added-large-files
        exclude: src/dbt/
      - id: check-json
        exclude: src/dbt/
      - id: check-merge-conflict
        exclude: src/dbt/
      - id: debug-statements
        exclude: src/dbt/
      - id: mixed-line-ending
        exclude: src/dbt/
      - id: check-xml
        exclude: src/dbt/
      - id: pretty-format-json
        exclude: src/dbt/
        args: [--autofix]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        exclude: src/dbt/
        additional_dependencies: [flake8-bugbear, flake8-bandit]
        args:
          - --ignore
          - W605, S101, E203, W503, B907
          - "--max-line-length=88"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.960"
    hooks:
      - id: mypy
        exclude: src/dbt/
        language_version: "3.10"
        args:
          - --ignore-missing-imports
          - --config-file
          - mypy_pre_commit.ini

  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.18.0
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: ['.[jinjafmt]']


  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.1.1
    hooks:
      - id: dbt-clean
        args:
          - --cmd-flags=--no-clean-project-files-only
      - id: dbt-deps
      - id: dbt-compile
        args:
          [
            "--cmd-flags",
            "++target",
            "ci",
            "--",
          ]
      - id: dbt-run
        args:
          [
            "--models",
            "*",
            "--cmd-flags",
            "++target",
            "ci",
            "--",
          ]
      - id: dbt-docs-generate
        args:
          [
            "--cmd-flags",
            "++target",
            "ci",
          ]
      - id: check-model-has-all-columns
      - id: check-model-has-description
        args: ["--exclude", "/macros/*|/docs/*", "--"]
      - id: check-model-has-tests-by-name
        name: Check the model has a unique test defined
        args: ["--tests", "unique=1", "--"]
      - id: check-source-has-freshness
        args: ["--freshness", "warn_after", "--"]
      - id: check-script-has-no-table-name
        args: [--ignore-dotless-table]
      - id: check-model-columns-have-desc
      - id: check-source-has-loader
      - id: check-model-has-properties-file
        exclude: "macros/"
      - id: check-column-desc-are-same
      - id: dbt-test
        args:
          [
            "--cmd-flags",
            "++target",
            "ci",
            "--",
          ]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ['dbt-bigquery==1.7.2', 'sqlfluff-templater-dbt']
