jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: data-platform-413021
      dataset: "dev_{{ env_var('USER') }}"
      threads: 4
    ci:
      type: bigquery
      method: oauth
      project: data-platform-413021
      dataset: "dev_{{ env_var('USER','ci') }}" # local collision with dev intended for pre-commit 
      threads: 4