version: 2

models:
  - name: stg_customers
    description: Staging model for customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
        description: Unique identifier for a customer
      - name: first_name
        description: Customer's first name. PII
      - name: last_name
        description: Customer's last name. PII

  - name: stg_orders
    description: Staging model for orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: Unique identifier for an order
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
        description: Status of the order. One of placed, shipped, completed, return_pending, returned.
      - name: customer_id
        description: Unique identifier for a customer
      - name: order_date
        description: Date (UTC) that the order was placed

  - name: stg_payments
    description: Staging model for payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
        description: Unique identifier for a payment
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
        description: Method of payment. One of credit_card, coupon, bank_transfer, gift_card.
      - name: order_id
        description: Unique identifier for an order
      - name: amount
        description: Total amount (AUD) of the payment