name: prod

on:
  workflow_dispatch:
  push:
  #schedule:
  #  - cron: "00 9 * * *"

permissions:
  contents: 'read'
  id-token: 'write'

env:
  DBT_PROFILES_DIR: src/jaffle_shop
  DBT_PROJECT_DIR: src/jaffle_shop
  DBT_TARGET_DIR: src/jaffle_shop/target
  DBT_KEYFILE_PATH: ${{ github.workspace }}/service_account.json

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set-up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/336697166112/locations/global/workloadIdentityPools/github/providers/data-platform
          service_account: data-platform@data-platform-413021.iam.gserviceaccount.com

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install -vv
        if: steps.cache.outputs.cache-hit != 'true'

      - name: dbt seed
        run: poetry run dbt seed --target prod

      - name: dbt run
        run: poetry run dbt run --target prod

      - name: dbt test
        run: poetry run dbt test --target prod

      - name: Upload dbt manifest to GCS
        id: upload-file
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
            path: '${{ env.DBT_TARGET_DIR }}'
            destination: 'data-platform'